// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whhckmzqeniizdkwgznf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoaGNrbXpxZW5paXpka3dnem5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzcxNDU4MjIsImV4cCI6MjA5MjcyMTgyMn0.diNYsixfHFXraEdu8EnrIZu-5Wb_6O1uD46zNlxy9ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});